compiler: /usr/bin/g++
mpic: /usr/bin/mpic++
    
# compiler flags (std=c++14 is necessary)
cflags: -std=c++14 -Wall -O3

# MPI mode
enable_mpi: 0

# GSL (GNU Scientific Library)
lgsl: -L/usr/local/lib
igsl: -I/usr/include
libgsl: -lgsl -lgslcblas

# MCIntegrator++ Library
mci_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/MCIntegratorPlusPlus

#NoisyFunctionMinimization Library
nfm_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/NoisyFunMin

#VMC++ Library
vmc_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/VMCPlusPlus

#QNets Library
qnets_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/QNets

#Sannifa Library
sannifa_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/sannifa

#NNVMC Library
nnvmc_dir: /home/ithanil/Resilio/PostMaster/Code/NNVMC/NNVMC
